my_string = input('Как Вас зовут? (дайте развернутый ответ): ')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string [0])
print(my_string [-1])
print("количество символов:" , len(my_string))
